# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np
a=6*np.ones((5,5))
b=np.zeros((3,3))
a[1:4,1:4]=b
print(a)

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [4]:
a=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if ((i+j)%2)==0:
            a[i,j]=3
        else:
            a[i,j]=9
print(a)

[[3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [8]:
a=np.empty((3,4))
print(a)
b=np.full((3,3),6)
print(b)


[[1.13669430e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 7.35370523e-043 2.83485836e-032 1.38214220e-047]
 [1.33689724e+165 2.72687355e-056 4.75166170e+174 4.01064036e+174]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [9]:
import numpy as np
a=[0,12,45.21,34,99.91]
b=(np.array(a)-32)*(5/9)
print("Values in farenheit",np.array(a))
print("Values in centigrade",b)

Values in farenheit [ 0.   12.   45.21 34.   99.91]
Values in centigrade [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [12]:
import numpy as np
a=np.array([ 1.00000000+0j,0.70710678+0.70710678j])
a=a[0]+a[1]
print(a.real)
print(a.imag)

1.7071067800000002
0.70710678


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [15]:
import numpy as np
a=np.array([0,10,20,40,60])
b=np.array([0,40])
c=np.in1d(a,b)
print(c)

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [16]:
import numpy as np
a=np.array([0,10,20,40,60])
b=np.array([0,40])
c=np.in1d(a,b)
print(a[c])

[ 0 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [17]:
import numpy as np
a=np.array([[10,10],[20,20],[60,70]])
b=a.flatten()
print(b)
print(np.asarray(list(set(b))))


[10 10 20 20 60 70]
[70 10 20 60]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [18]:
import numpy as np
Array1=[0,10,20,40,60,80]
Array2=[10, 30, 40, 50, 70]
print(np.setxor1d(Array1,Array2))

[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [19]:
import numpy as np
Array1=[-50,10,20,40,60,80]
print(np.all(Array1))

True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [20]:
import numpy as np
Array1=[[0,10,20],[40,60,80]]
print(np.all(Array1,axis=1))

[False  True]


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [21]:
import numpy as np
a=[1,2,3,4]
print(np.tile(a,1))
print(np.tile(a,2))
print(np.tile(a,3))

[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [23]:
import numpy as np
a=[1,2,3,4,5,6]
print(np.argmax(a))
print(np.argmin(a))

5
0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [24]:
import numpy as np
a=[1,2]
b=[4,5]
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))
print(np.less_equal(a,b))

[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [28]:
import numpy as np
a=[[4,6],[2,1]]
print("sort along first axis:",np.sort(a,axis=0))
print("sort along last axis:",np.sort(a,axis=-1))

sort along first axis: [[2 1]
 [4 6]]
sort along last axis: [[4 6]
 [1 2]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [35]:
import numpy as np
first_names=('Betsey','Shelley','Lanell','Genesis','Margery')
last_names=('Brien','Woolum','Battle','Plotner','Stahl')
a=np.lexsort((first_names, last_names))
print(a)


[2 0 3 4 1]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [30]:
import numpy as np
a=np.array([[10,20,30],[30,40,50]])
b=a.flatten()
print("Values bigger than 10:",a[np.where(a>10)])
c=np.where(a>10)
print("Their indices are",c)

Values bigger than 10: [20 30 30 40 50]
Their indices are (array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [31]:
import numpy as np
a=np.ones((2,8))
print(a.size*a.itemsize)

128


## Great Job!