# Assignment

Q1. Create two arrays of six elements. Write the NumPy program to
count the number of instances of a value occurring in one array on
the condition of another array.

    Sample OutputOriginal arrays-
    [ 10 -10 10 -10 -10 10]
    [0.85 0.45 0.9 0.8 0.12 0.6 ]
    Number of instances of a value occurring in one array on the condition of another
    array: 3


In [4]:
import numpy as np
a=np.array([10,-10,10,-10,-10,10])
b=np.array([0.85,0.45,0.9,0.8,0.12,0.6])
result=np.sum((a==10) & (b>0.5))
print(result)

3


Q2. Write the NumPy program to convert a Python dictionary to a
Numpy ndarray ?
    
    Original dictionary-
    {'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
    'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
    'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
    'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
    Type: <class 'dict'>
    ndarray-
    [[ 1. 0. 0. 2.]
    [ 3. 1. 0. -1.]
    [ 4. 1. 5. -1.]
    [ 3. -1. -1. -1.]]
    Type: <class 'numpy.ndarray'>


In [42]:
a={'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
type(a)
#print(a.keys())
b=[]
c=len(a.keys())
for i,k in a.items():
    for j,l in k.items():
        b.append(l)
np.array(b).reshape(c,c)
        

array([[ 1.,  0.,  0.,  2.],
       [ 3.,  1.,  0., -1.],
       [ 4.,  1.,  5., -1.],
       [ 3., -1., -1., -1.]])

Q3. Write the Numpy program to find and store the non-zero unique
rows in an array after comparing each row with other row in the
given matrix?
 
    Original array-
    [[ 1 1 0]
    [ 0 0 0]
    [ 0 2 3]
    [ 0 0 0]
    [ 0 -1 1]
    [ 0 0 0]]
    Non-zero unique rows-
    [[ 1 1 0]
    [ 0 2 3]
    [ 0 -1 1]]

In [87]:
a=np.array([[1,1,0],
[0,1,0],
[0,2,3],
[0,1,0],
[0,-1,1],
[0,0,0]])

c=[]
b=len(a[0])
col=int(a.size/b)
for i in range(col):
    if np.any(a[i]):
        c.append(a[i])
print(np.unique(np.array(c),axis=0))
np.any(a[1])

[[ 0 -1  1]
 [ 0  1  0]
 [ 0  2  3]
 [ 1  1  0]]


True

Q4. Write the NumPy program to multiply the matrix by another matrix
of complex numbers and create a new matrix of complex
numbers?

    Sample outputFirst array-
    [ 1.+2.j 3.+4.j]
    Second array-
    [ 5.+6.j 7.+8.j]
    Product of above two arrays-
    (70-8j)

Q5. Write a NumPy program to generate the matrix product of two
Arrays?

    Sample OutputMatrices and vectors.
    x-
    [[1, 0], [1, 1]]
    y-
    [[3, 1], [2, 2]]
    Matrix product of above two arrays-
    [[3 1]
    [5 3]]


In [99]:
x=np.array([[1,0],[1,1]])
y=np.array([[3,1],[2,2]])
print(x@y)

[[3 1]
 [5 3]]


Q6. Write the NumPy program to find roots of the following
Polynomials?

    a) (x
    2
    - 4x + 7)
    b) x4
    - 11x3 + 9x2 + 11x ? 10
    Sample outputRoots of the first polynomial-
    [ 1. 1.]
    Roots of the second polynomial-
    [ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j
    0.91326132-0.4531004j ]

In [105]:
coeff1=[1,-4,7]
coeff2=[1,-11,9,11,10]
print(np.roots(coeff1))
print(np.roots(coeff2))

[2.+1.73205081j 2.-1.73205081j]
[ 9.97739366+0.j          1.9206355 +0.j         -0.44901458+0.56588568j
 -0.44901458-0.56588568j]


Q7. Write the NumPy program to calculate inverse of sine, cosine,
and inverse tangent for all elements in a given array?

    Sample outputInverse sine- [-1.57079633 0. 1.57079633]
    Inverse cosine- [3.14159265 1.57079633 0. ]
    Inverse tangent- [-0.78539816 0. 0.78539816]

In [134]:
import math
a=[1,0,-1]
print('sin inverse:',np.arcsin(a))
print('cos inverse:',np.arccos(a))
print('tan inverse:',np.arctan(a))

sin inverse: [ 1.57079633  0.         -1.57079633]
cos inverse: [0.         1.57079633 3.14159265]
tan inverse: [ 0.78539816  0.         -0.78539816]


Q8. Write the NumPy program to calculate the difference between in
neighbouring elements, element-wise of a given array?

    Sample outputOriginal array-
    [1 3 5 7 0]
    Difference between neighbouring elements, element-wise of the said array-
    [ 2 2 2 -7]

In [138]:
a=[1,3,5,7,0]
print(np.ediff1d(a))

[ 2  2  2 -7]


Q9. Write the Python program to find the maximum and the minimum
value of a given flattened array?

    Expected OutputOriginal flattened array-
    [[0 1]
    [2 3]]
    Maximum value of the above flattened array3
    Minimum value of the above flattened array0

In [141]:
a=np.array([[0,1],[2,3]])
print("Maximum value of the above flattened array:",np.max(a))
print("Minimum value of the above flattened array:",np.min(a))

Maximum value of the above flattened array: 3
Minimum value of the above flattened array: 0


Q10. Write the NumPy program to calculate the difference between in
the maximum and the minimum values of a given array along the
second axis ?

    Expected OutputOriginal array-
    [[ 0 1 2 3 4 5]
    [ 6 7 8 9 10 11]]
    Difference between the maximum and the minimum values of the said array-
    [5 5]


In [143]:
a=np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
print(np.ptp(a,1))

[5 5]


Q11. Write the NumPy program to compute the weighted of the given
array ?

    Sample OutputOriginal array-
    [0 1 2 3 4]
    Weighted average of the said array2.6666666666666665

In [164]:
a=np.arange(5)
print(np.average(a,weights=[1,2,3,4,5]))

2.6666666666666665


Q12. Write the NumPy program to compute the mean, standard
deviation, and the variance of a given array along the second
axis?

    Sample outputOriginal array-
    [0 1 2 3 4 5]
    Mean- 2.5
    std- 1
    variance- 2.9166666666666665

In [174]:
import statistics as st
a=np.array([0,1,2,3,4,5])
print(np.average(a))
print(np.std(a))
print(np.var(a))

2.5
1.707825127659933
2.9166666666666665


Q13. Write the Numpy program to compute the covariance matrix of the
two given arrays?
    
    Sample OutputOriginal array1-
    [0 1 2]
    Original array1-
    [2 1 0]
    Covariance matrix of the said arrays-
    [[ 1. -1.]
    [-1. 1.]]

In [176]:
a=np.array([0,1,2])
b=np.array([2,1,0])
print(np.cov(a,b))

[[ 1. -1.]
 [-1.  1.]]


Q14. Write a NumPy program to compute the cross-correlation of two
given arrays ?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Cross-correlation of the said arrays-
    [ [ 2.33333333 2.16666667 ]
     [ 2.16666667 2.33333333 ] ]

In [183]:
a=np.array([0,1,3])
b=np.array([2,4,5])
np.cov(a,b,"full")

array([[2.33333333, 2.16666667],
       [2.16666667, 2.33333333]])

Q15. Write the NumPy program to compute Pearson product-moment
correlation coefficients of two given arrays?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Pearson product-moment correlation coefficients of the said arrays-
    [[1. 0.92857143]
    [0.92857143 1. ]]

In [186]:
a=np.array([0,1,3])
b=np.array([2,4,5])
np.corrcoef(a,b,"full")

array([[1.        , 0.92857143],
       [0.92857143, 1.        ]])

Q16. Write the python program to count the number of occurrences of
each value in a given array of non-negative integers?
 
Note: bincount() Function- It count the occurrence of each value in an array of the
non- negative integers in the range of the array between the minimum and maximum values
including the values that did not occur.

    Sample OutputOriginal array-
    [0, 1, 6, 1, 4, 1, 2, 2, 7]
    Number of occurrences of each value in array-
    [1 3 2 0 1 0 1 1]

In [187]:
a=np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
print(np.bincount(a))

[1 3 2 0 1 0 1 1]


Q17. Write a Numpy program to compute the histogram of nums
against the bins?

    Sample Outputnums- [0.5 0.7 1. 1.2 1.3 2.1]
    P a g e 29 | 44
    bins- [0 1 2 3]
    Result- (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [194]:
nums=np.array([0.5,0.7,1.,1.2,1.3,2.1])
bins=np.array([0,1,2,3])
print(np.histogram(nums,bins))

(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))


## Great Job!